### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by maiorfi** [shapelets/khiva-python#56]
**Describe the bug**
I get a access violation whenever I use khiva python lib

**To Reproduce**
Run a simple program like:

```python
from khiva.library import *
set_backend(KHIVABackend.KHIVA_BACKEND_OPENCL)
set_device(0)

from khiva.array import *
a = Array([1, 2, 3, 4, 5, 6, 7, 8])
a.display()
```

**Expected behavior**
Application should run without exceptions

**Screenshots**
```
(base) C:\Progetti\Lab\Khiva\MyPythonSamples\HelloKhiva>python main.py
array
[8 1 1 1]
    1.0000
    2.0000
    3.0000
    4.0000
    5.0000
    6.0000
    7.0000
    8.0000

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    a.display()
  File "C:\Anaconda3\lib\site-packages\khiva\array.py", line 323, in display
    KhivaLibrary().c_khiva_library.display(ctypes.pointer(self.arr_reference))
OSError: exception: access violation writing 0x00007FFE94CB180A
```

**Environment information:**
 - OS: Windows 10
 - Version 0.3.0

**Comment by avilchess** [comment]
Hi Lorenzo,

We are investigating this issue, in the meantime could you tell us if you downloaded the code directly from master or from a tagged version? It happens that both master branches are not synchronized right now. 

Please tell us how you installed **khiva** and **khiva-python**. This way we can provide you a fast solution for this issue.

Antonio Vilches.

**Comment by maiorfi** [comment]
I installed khiva native stuff through installer "khiva-v0.4.0.exe" and python library with "pip install khiva" .

Thanks.

**Comment by avilchess** [comment]
Hi again Lorenzo,

We are currently working on the release of the version 0.4.0 of **khiva-python**, this version should fix the problems you are facing right now. If you want to solve this issue, you need to clone the branch **feature/errorHandling** and install this version of the library by executing the following command from the root folder of the repo:
```
python setup.py install
```

It should fix your issue, note this is just a temporary fix, as we will merge that branch into master and release the new version of **khiva-python** anytime soon. Please, tell us if this problem disappears with the proposed solution.

Regards,
Antonio Vilches.

**Comment by maiorfi** [comment]
Hi Antonio.

Sadly I get same error as before.

This is the output I get:

```
Khiva Library Version 0.4.0
array
[8 1 1 1]
    1.0000 
    2.0000 
    3.0000 
    4.0000 
    5.0000 
    6.0000 
    7.0000 
    8.0000 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Progetti/Lab/Khiva/MyPythonSamples/HelloKhiva/main.py", line 16, in <module>
    runSample()
  File "C:/Progetti/Lab/Khiva/MyPythonSamples/HelloKhiva/main.py", line 8, in runSample
    a.display()
  File "C:\Anaconda3\lib\site-packages\khiva\array.py", line 323, in display
    KhivaLibrary().c_khiva_library.display(ctypes.pointer(self.arr_reference))
OSError: exception: access violation writing 0x00007FFCB2C8180A

Process finished with exit code 1
```

Thanks :)

**Comment by avilchess** [comment]
Hi Lorenzo, 

It may be that Conda is not finding the version you downloaded and installed manually. 
May I suggest you to remove both versions and just installing again the second one?

Another solution just popped my mind: You can delete your khiva 0.4.0 version and install the 0.3.0 one which should work well with the version 0.3.5 of khiva-python.

In the meanwhile, I'm working with my colleagues to merge feature/erroHandling branch and deploying the nerversion yo Pypi. I strongly believe this is the best way to fix your issue.

Andotnio Vilches.

**Comment by maiorfi** [comment]
I double checked and my python app is actually loading the right lib version. On the contrary, the other solution (using 0.3.0 native library) works fine.

Thanks!
