### ISSUE TITLE
Khiva Python Bindings not passing all unit tests

### ISSUE THREAD

**Issue by yuhongsun96** [shapelets/khiva-python#59]
**Describe the bug**
Khiva Python Bindings not passing all unit tests. Problems include seg fault or is not able to find required library in khiva function call. 

**To Reproduce**
Build khiva from source, install. Run install script to generate python bindings. Run unit tests from this repo. 

**Expected behavior**
All tests should pass.

**Environment information:**
Ubuntu 18.04.4 LTS
Python 3.6.9
Conan version 1.23.0
ArrayFire-v3.6.2

**Additional context**
I joined the Gitter, it may be easier to continue the conversation there.
Saw no errors during installation of both khiva and the python bindings. Prerequisites were installed prior to installing khiva.

**Comment by raulbocanegra** [comment]
Fixed on #60
